-- MySQL Script generated by MySQL Workbench
-- Tue Nov 14 19:18:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ong
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ong` ;

-- -----------------------------------------------------
-- Schema ong
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ong` DEFAULT CHARACTER SET utf8 ;
USE `ong` ;

-- -----------------------------------------------------
-- Table `ong`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ong`.`users` ;

CREATE TABLE IF NOT EXISTS `ong`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `organization_name` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ong`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ong`.`projects` ;

CREATE TABLE IF NOT EXISTS `ong`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `inital_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_proyecto_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ong`.`users_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ong`.`users_projects` ;

CREATE TABLE IF NOT EXISTS `ong`.`users_projects` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_users_has_projects_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_users_has_projects_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_projects_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `ong`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_projects_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `ong`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
